module.exports = [
  {
    title: "Atomic Habits",
    author: "James Clear",
    price: 19.99,
    oldPrice: 29.99,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f",
    rating: 5,
    category: "Self Development",
    badge: "Best Seller",
    stock: 120,
    pages: 320,
    language: "English",
    publisher: "Avery",
    featured: true,
    tags: ["habits", "productivity", "psychology"],
    description:
      "Practical strategies to build good habits, break bad ones, and make small changes that compound into big results.",
  },
  {
    title: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    price: 14.99,
    oldPrice: 24.99,
    image: "https://images.unsplash.com/photo-1512820790803-83ca734da794",
    rating: 4,
    category: "Business",
    badge: "Popular",
    stock: 80,
    pages: 336,
    publisher: "Plata Publishing",
    featured: true,
    tags: ["money", "investing"],
    description:
      "Personal finance lessons contrasting two perspectives on money, investing, and financial independence.",
  },
  {
    title: "The Psychology of Money",
    author: "Morgan Housel",
    price: 17.99,
    oldPrice: 27.99,
    image: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da",
    rating: 5,
    category: "Finance",
    badge: "Hot",
    stock: 95,
    pages: 252,
    publisher: "Harriman House",
    featured: true,
    tags: ["money", "behaviour"],
    description:
      "Timeless stories and insights about how people think about money and how that affects financial decisions.",
  },
  {
    title: "Deep Work",
    author: "Cal Newport",
    price: 16.5,
    oldPrice: 26.5,
    image: "https://images.unsplash.com/photo-1516979187457-637abb4f9353",
    rating: 4,
    category: "Productivity",
    badge: "New",
    stock: 60,
    pages: 304,
    publisher: "Grand Central Publishing",
    tags: ["focus", "productivity"],
    description:
      "Rules for focused success in a distracted world, and a practical system for producing work that matters.",
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 12.99,
    oldPrice: 19.99,
    image: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d",
    rating: 5,
    category: "Novel",
    badge: "Classic",
    stock: 150,
    pages: 208,
    publisher: "HarperOne",
    featured: true,
    tags: ["fiction", "journey"],
    description:
      "A shepherd boy travels from Spain to Egypt in search of treasure and discovers what he was really looking for.",
  },
  {
    title: "Clean Code",
    author: "Robert C. Martin",
    price: 34.99,
    oldPrice: 49.99,
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765",
    rating: 5,
    category: "Programming",
    badge: "Best Seller",
    stock: 45,
    pages: 464,
    publisher: "Prentice Hall",
    featured: true,
    tags: ["software", "craftsmanship"],
    description:
      "A handbook of agile software craftsmanship, full of practical advice on writing code that other people can read.",
  },
  {
    title: "Can't Hurt Me",
    author: "David Goggins",
    price: 21.0,
    oldPrice: 30.0,
    image: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e",
    rating: 5,
    category: "Motivation",
    badge: "Hot",
    stock: 70,
    pages: 364,
    publisher: "Lioncrest Publishing",
    tags: ["discipline", "mindset"],
    description:
      "A memoir about turning suffering into strength, and the mental frameworks behind extraordinary endurance.",
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 15.99,
    oldPrice: 22.99,
    image: "https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf",
    rating: 5,
    category: "Fantasy",
    badge: "Classic",
    stock: 110,
    pages: 310,
    publisher: "Houghton Mifflin",
    tags: ["fantasy", "adventure"],
    description:
      "Bilbo Baggins is swept into a quest to reclaim a treasure guarded by a dragon, and returns home changed.",
  },
  {
    title: "Ikigai",
    author: "Hector Garcia",
    price: 13.75,
    oldPrice: 20.0,
    image: "https://images.unsplash.com/photo-1519681393784-d120267933ba",
    rating: 4,
    category: "Lifestyle",
    badge: "Popular",
    stock: 85,
    pages: 208,
    publisher: "Penguin Life",
    tags: ["wellbeing", "japan"],
    description:
      "The Japanese secret to a long and happy life, drawn from the habits of the world's longest-living communities.",
  },
  {
    title: "Into the Wild",
    author: "Jon Krakauer",
    price: 14.25,
    oldPrice: 21.5,
    image: "https://images.unsplash.com/photo-1476275466078-4007374efbbe",
    rating: 4,
    category: "Adventure",
    badge: "New",
    stock: 55,
    pages: 224,
    publisher: "Anchor Books",
    tags: ["travel", "true story"],
    description:
      "The true story of a young man who gave away his savings and walked alone into the Alaskan wilderness.",
  },
];
